services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=tavily_research
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - MONGODB_URI="mongodb+srv://tamirkatz1234:a62CoHwmwpmHNQ5f@executive.e6ythg6.mongodb.net/?retryWrites=true&w=majority&appName=executive"
    volumes:
      - ./reports:/app/reports
      - ./backend:/app/backend
      - ./application.py:/app/application.py
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    image: node:20-slim
    working_dir: /ui
    command: sh -c "npm install && npm run dev"
    ports:
      - "5174:5174"
    volumes:
      - ./ui:/ui
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000

volumes:
  mongodb_data:
